version: 2

builds:
  - main: ./cmd/mongospectre/
    binary: mongospectre
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

dockers:
  - image_templates:
      - "ghcr.io/ppiankov/mongospectre:{{ .Version }}-amd64"
    dockerfile: Dockerfile.goreleaser
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
    goarch: amd64

  - image_templates:
      - "ghcr.io/ppiankov/mongospectre:{{ .Version }}-arm64"
    dockerfile: Dockerfile.goreleaser
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64"
    goarch: arm64

brews:
  - repository:
      owner: ppiankov
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/ppiankov/mongospectre"
    description: "MongoDB collection and index auditor — detects drift between code and live clusters"
    license: MIT
    install: |
      bin.install "mongospectre"
    test: |
      system "#{bin}/mongospectre", "version"

docker_manifests:
  - name_template: "ghcr.io/ppiankov/mongospectre:{{ .Version }}"
    image_templates:
      - "ghcr.io/ppiankov/mongospectre:{{ .Version }}-amd64"
      - "ghcr.io/ppiankov/mongospectre:{{ .Version }}-arm64"

  - name_template: "ghcr.io/ppiankov/mongospectre:latest"
    image_templates:
      - "ghcr.io/ppiankov/mongospectre:{{ .Version }}-amd64"
      - "ghcr.io/ppiankov/mongospectre:{{ .Version }}-arm64"
